before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: zg7zp0B+YGDEae6Fne3UlzrNAd3BGQYZlcUSj0Pe4hs51zKXPCcNvQEK0SlLuJAtdOdBEIYxwu+WZFDU7uyIVu/A8T+J0hf9WXHP2OX1vyiS0DdKdYFiATDpDgdRYzE0H/9TADZkFN6h6JYV3jtGig6O0OwyH1fWRaq7gU9HOWCSqNXQSzgJ8054/AqrMrqZYxfbt5lRBF+YYk0z5SkpsPi+P8gmfje+LFnSh4n3bhWTbIh6sBTPzpoU68yDR5isxIeaBdxIvLC+9dhHJ1FUHTZKFo94yWKVbQlaUiPpts4E0aahqXBtWrZgFRLjjjDataZJlSN+o3vNUhrqMSb8ERUlwbY+/6Bz6HQRO8HksCrOIt5uwPh6TVa4kUdAkNxaNRuNCA7MNJT1HRxq6tBwGmePMx+Dd2P5wQEOWEjb+S71fmM6PI+Xj8Kupb3+gZnPGEodzyq8RnLQ7r6gqp1XNJqgk5XhzSfwpLE+CUdSbc9gNHe/t0ypy0Ij9CMPqGhfqSB7Gw/GAtbvNgqES8MUaY05supRhnqUtWqYZ3If7MRP6YRIWhAfVDBvi5ILEd7jLN2rTS56fJy9yzk0GmmLIsj83SxM68guWermdWcyl96vEitL/ZgRYwDZuHICgwZVaNAkK1XYdwjdz/Rn2TtP37MqQAdhdTKZR44D3x3qTR0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
